@echo off
echo Deleting HIV and SIDER cache...
if exist "data\HIV" rmdir /s /q "data\HIV"
if exist "data\SIDER" rmdir /s /q "data\SIDER"
echo Creating K=2 script...
python make_k2.py
echo Starting MoE K=2 training...
python attentivefp_moe_k2.py
